title: TidyTuesday
url: https://tidytuesday.seanlunsford.com
description: Weekly(-ish) adventures in data visualization
author: Sean Lunsford
repo: https://github.com/slunsford/tidytuesday
tidytuesday_base: https://github.com/rfordatascience/tidytuesday/blob/main/data
